# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('PYT', 'Python'), ('PAS', 'Pascal'), ('CPP', 'C++')], default='PYT', max_length=3, verbose_name='Язык')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема')),
                ('article', models.TextField(blank=True, null=True, verbose_name='Описание темы')),
            ],
        ),
    ]
