# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-17 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180314_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['language', 'number_theme'], 'verbose_name': 'Тема курса', 'verbose_name_plural': 'Темы курса'},
        ),
        migrations.AddField(
            model_name='course',
            name='url_video',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Url-видео'),
        ),
    ]
