# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-20 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20180317_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_keywords',
            field=models.TextField(blank=True, max_length=160, verbose_name='Keywords'),
        ),
    ]
