# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-20 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20180320_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='seo_description',
        ),
    ]
