# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-04 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_course_seo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputOutputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='Входные данные')),
                ('output', models.TextField(verbose_name='Выходные данные')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('url_ref', models.URLField(blank=True, verbose_name='Ссылка')),
                ('condition', models.TextField(blank=True, verbose_name='Условие задачи')),
                ('difficult', models.IntegerField(verbose_name='Сложность')),
                ('examples', models.ManyToManyField(blank=True, to='videos.InputOutputData', verbose_name='Примеры')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='videos.ProgrammTask', verbose_name='задачи'),
        ),
    ]
