# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-30 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20180807_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('PYT', 'Python'), ('PAS', 'Pascal'), ('CPP', 'C++'), ('TUR', 'Turtle')], default='PYT', max_length=3, verbose_name='Язык'),
        ),
    ]
