# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-01-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20190131_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('PYT', 'Python'), ('PAS', 'Pascal'), ('CPP', 'C++'), ('TUR', 'Turtle'), ('PGA', 'Pygame')], default='PYT', max_length=3, verbose_name='Язык'),
        ),
    ]
