# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-01-14 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
