# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-01-14 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20200114_2058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([]),
        ),
    ]
