# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-01-31 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20200114_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stepic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stepic'),
        ),
    ]
