# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-04-05 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_course_stepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmtask',
            name='decision',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Url-видеорешение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('PYT', 'Python'), ('PAS', 'Pascal'), ('CPP', 'C++'), ('TUR', 'Turtle'), ('PGA', 'Pygame'), ('OOP', 'OOP Python')], default='PYT', max_length=3, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='course',
            name='stepic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stepic'),
        ),
    ]
