# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-04-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_auto_20200405_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmtask',
            name='patreon',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Patreon'),
        ),
    ]
