# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_auto_20200131_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmtask',
            name='decision',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Url-видеорешение'),
        ),
    ]
