# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-04-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_programmtask_patreon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmtask',
            name='patreon',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка'),
        ),
    ]
