# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-04-05 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_auto_20200405_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_closed_video',
            field=models.BooleanField(default=False, verbose_name='Для спонсоров'),
        ),
    ]
