# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-04-05 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_course_is_closed_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='patreon',
            field=models.URLField(blank=True, default='', verbose_name='Patreon'),
        ),
    ]
