# Generated by Django 3.2 on 2021-12-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_course_boosty'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmtask',
            name='boosty',
            field=models.URLField(blank=True, default='', verbose_name='Boosty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('PYT', 'Python'), ('PAS', 'Pascal'), ('CPP', 'C++'), ('TUR', 'Turtle'), ('PGA', 'Pygame'), ('OOP', 'OOP Python'), ('TKN', 'Tkinter')], default='PYT', max_length=3, verbose_name='Язык'),
        ),
    ]
