# Generated by Django 3.2 on 2022-01-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0021_auto_20211231_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('PYT', 'Python'), ('PAS', 'Pascal'), ('CPP', 'C++'), ('TUR', 'Turtle'), ('PGA', 'Pygame'), ('OOP', 'OOP Python'), ('TKN', 'Tkinter'), ('DJA', 'Django')], default='PYT', max_length=3, verbose_name='Язык'),
        ),
    ]
