# Generated by Django 5.2 on 2026-04-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_alter_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rutube_id',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Rutube ID'),
        ),
        migrations.RenameField(
            model_name='course',
            old_name='url_video',
            new_name='youtube_id',
        ),
    ]
