# Generated by Django 5.2 on 2026-04-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_remove_course_url_video_course_rutube_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='YouTube ID'),
        ),
    ]
