# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-02 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTheory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория вопросов ЕГЭ',
                'verbose_name_plural': 'Категории теории',
            },
        ),
        migrations.CreateModel(
            name='TheoryVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('url_video', models.CharField(max_length=50, verbose_name='Url-видео')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.CategoryTheory', verbose_name='Категория видео')),
            ],
            options={
                'verbose_name': 'Теория',
                'verbose_name_plural': 'Теория по экзаменам',
            },
        ),
    ]
