# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-02 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theoryvideo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
