# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория вопросов ЕГЭ',
                'verbose_name_plural': 'Категории вопросов ЕГЭ',
                'ordering': ['number_task'],
            },
        ),
        migrations.CreateModel(
            name='NumberTaskEge',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер задания')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, default='', upload_to='ege/photo')),
                ('type_of_answer', models.CharField(choices=[('ManyT', 'ManyText'), ('Input', 'Input')], default='Input', max_length=5)),
            ],
            options={
                'verbose_name': 'Номер задания ЕГЭ',
                'verbose_name_plural': 'Номера заданий ЕГЭ',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionsEGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('picture', models.ImageField(blank=True, default='', upload_to='ege/photo')),
                ('table_data', models.TextField(blank=True, null=True, verbose_name='Табличные данные')),
                ('code_python', models.TextField(blank=True, null=True, verbose_name='Python')),
                ('code_pascal', models.TextField(blank=True, null=True, verbose_name='Paskal')),
                ('code_c_plus', models.TextField(blank=True, null=True, verbose_name='C++')),
                ('answer', models.CharField(max_length=30, verbose_name='Ответ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ege.CategoryEge', verbose_name='Категория вопроса')),
                ('number_of_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ege.NumberTaskEge', verbose_name='Номер задания')),
            ],
            options={
                'verbose_name': 'Вопрос ЕГЭ',
                'verbose_name_plural': 'Вопросы ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='VarEge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_var', models.IntegerField(unique=True, verbose_name='Номер варианта')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вариант ЕГЭ',
                'verbose_name_plural': 'Варианты ЕГЭ',
            },
        ),
        migrations.AddField(
            model_name='questionsege',
            name='number_of_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ege.VarEge', verbose_name='Номер варианта'),
        ),
        migrations.AddField(
            model_name='categoryege',
            name='number_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ege.NumberTaskEge', verbose_name='Номер задания'),
        ),
    ]
