# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsege',
            name='number_of_variant',
        ),
        migrations.DeleteModel(
            name='VarEge',
        ),
    ]
