# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0003_auto_20170503_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsege',
            name='code_executor',
            field=models.TextField(blank=True, null=True, verbose_name='Испольнитель'),
        ),
    ]
