# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0004_questionsege_code_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbertaskege',
            name='seo_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='numbertaskege',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='numbertaskege',
            name='seo_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='varege',
            name='seo_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='varege',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='varege',
            name='seo_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title'),
        ),
    ]
