# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0006_remove_numbertaskege_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbertaskege',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='numbertaskege',
            name='seo_keywords',
            field=models.TextField(blank=True, max_length=160, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='numbertaskege',
            name='seo_title',
            field=models.TextField(blank=True, max_length=60, verbose_name='Title'),
        ),
    ]
