# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0007_auto_20171011_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbertaskege',
            name='seo_title',
        ),
    ]
