# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-23 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0010_auto_20171012_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.CharField(blank=True, max_length=50, null=True, verbose_name='Url-видео')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ege.QuestionsEGE', verbose_name='Вопрос')),
            ],
        ),
    ]
