# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0011_videoege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoege',
            name='question',
        ),
        migrations.AddField(
            model_name='questionsege',
            name='url_video',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Url-видео'),
        ),
        migrations.DeleteModel(
            name='VideoEge',
        ),
    ]
