# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-14 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0013_auto_20180614_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videorazborege',
            options={'verbose_name': 'Вариант ЕГЭ', 'verbose_name_plural': 'Варианты ЕГЭ'},
        ),
        migrations.AddField(
            model_name='videorazborege',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='videorazborege',
            name='seo_keywords',
            field=models.TextField(blank=True, max_length=160, verbose_name='SEO Keywords'),
        ),
    ]
