# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-14 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0014_auto_20180614_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videorazborege',
            options={'verbose_name': 'Разбор задач ЕГЭ', 'verbose_name_plural': 'Разборы ЕГЭ'},
        ),
        migrations.RemoveField(
            model_name='questionsege',
            name='url_video',
        ),
        migrations.AddField(
            model_name='questionsege',
            name='q_url_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ege.VideoRazborEGE', verbose_name='Url-видео'),
        ),
    ]
