# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-04 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0015_auto_20180614_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videorazborege',
            name='description',
        ),
    ]
