# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-08 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ege', '0018_auto_20180803_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsege',
            name='code_executor',
        ),
    ]
