# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-14 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ege', '0019_remove_questionsege_code_executor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task_ege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ege.QuestionsEGE', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
