services:
  mysql:
    image: mysql:8.4
    container_name: django_mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "${DB_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

    command: >
      --mysql-native-password=ON
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_allowed_packet=256M

  adminer:
    image: adminer
    container_name: django_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  mysql_data: