# Generated by Django 3.2 on 2022-01-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theory', '0002_auto_20180803_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория вопросов ОГЭ',
                'verbose_name_plural': 'Категории вопросов ОГЭ',
                'ordering': ['number_task'],
            },
        ),
        migrations.CreateModel(
            name='NumberTaskOge',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер задания')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('picture', models.ImageField(blank=True, default='', upload_to='oge/photo')),
                ('type_of_answer', models.CharField(choices=[('Radio', 'RadioButton'), ('Input', 'Input'), ('NoInp', 'NoInput')], default='Input', max_length=5)),
                ('seo_description', models.TextField(blank=True, max_length=160, verbose_name='Description')),
                ('seo_keywords', models.TextField(blank=True, max_length=160, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Номер задания ОГЭ',
                'verbose_name_plural': 'Номера заданий ОГЭ',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='VariantOge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_var', models.IntegerField(unique=True, verbose_name='Номер задания')),
            ],
            options={
                'verbose_name': 'Вариант ОГЭ',
                'verbose_name_plural': 'Варианты ОГЭ',
            },
        ),
        migrations.CreateModel(
            name='VideoRazborOGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.CharField(blank=True, max_length=50, null=True, verbose_name='Url-видео')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('seo_description', models.TextField(blank=True, max_length=160, verbose_name='SEO Description')),
                ('seo_keywords', models.TextField(blank=True, max_length=160, verbose_name='SEO Keywords')),
                ('number_of_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oge.numbertaskoge', verbose_name='Номер задания')),
                ('treoryKnowledge', models.ManyToManyField(blank=True, to='theory.TheoryVideo', verbose_name='Теория')),
            ],
            options={
                'verbose_name': 'Разбор задач ОГЭ',
                'verbose_name_plural': 'Разборы ОГЭ',
            },
        ),
        migrations.CreateModel(
            name='QuestionsOge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('picture', models.ImageField(blank=True, default='', upload_to='oge/photo')),
                ('table_data', models.TextField(blank=True, null=True, verbose_name='Табличные данные')),
                ('code_python', models.TextField(blank=True, null=True, verbose_name='Python')),
                ('code_pascal', models.TextField(blank=True, null=True, verbose_name='Paskal')),
                ('code_c_plus', models.TextField(blank=True, null=True, verbose_name='C++')),
                ('var_of_choice_answer', models.TextField(blank=True, null=True, verbose_name='Варианты ответа')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл')),
                ('failed', models.IntegerField(default=0, verbose_name='Неверные попытки')),
                ('passed', models.IntegerField(default=0, verbose_name='Правильные попытки')),
                ('answer', models.CharField(max_length=30, verbose_name='Ответ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oge.categoryoge', verbose_name='Категория вопроса')),
                ('number_of_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oge.numbertaskoge', verbose_name='Номер задания')),
                ('number_of_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oge.variantoge', verbose_name='Номер варианта')),
                ('q_url_video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oge.videorazboroge', verbose_name='Url-видео')),
            ],
            options={
                'verbose_name': 'Вопрос ОГЭ',
                'verbose_name_plural': 'Вопросы ОГЭ',
            },
        ),
        migrations.AddField(
            model_name='categoryoge',
            name='number_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oge.numbertaskoge', verbose_name='Номер задания'),
        ),
    ]
