# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantoge',
            old_name='description',
            new_name='opisanie',
        ),
    ]
