# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0002_auto_20170928_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantoge',
            old_name='opisanie',
            new_name='description',
        ),
    ]
