# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0004_questionsoge_code_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbertaskoge',
            name='id',
        ),
        migrations.AlterField(
            model_name='numbertaskoge',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер задания'),
        ),
        migrations.AlterField(
            model_name='variantoge',
            name='number_var',
            field=models.IntegerField(unique=True, verbose_name='Номер задания'),
        ),
    ]
