# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0008_remove_numbertaskoge_seo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbertaskoge',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='numbertaskoge',
            name='seo_keywords',
            field=models.TextField(blank=True, max_length=160, verbose_name='Keywords'),
        ),
    ]
