# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0010_auto_20171012_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRazborOGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.CharField(blank=True, max_length=50, null=True, verbose_name='Url-видео')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('seo_description', models.TextField(blank=True, max_length=160, verbose_name='SEO Description')),
                ('seo_keywords', models.TextField(blank=True, max_length=160, verbose_name='SEO Keywords')),
                ('number_of_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oge.NumberTaskOge', verbose_name='Номер задания')),
            ],
            options={
                'verbose_name': 'Разбор задач ОГЭ',
                'verbose_name_plural': 'Разборы ОГЭ',
            },
        ),
        migrations.AddField(
            model_name='questionsoge',
            name='q_url_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oge.VideoRazborOGE', verbose_name='Url-видео'),
        ),
    ]
