# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_auto_20180803_0018'),
        ('oge', '0011_auto_20180704_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorazboroge',
            name='treoryKnowledge',
            field=models.ManyToManyField(blank=True, to='theory.TheoryVideo', verbose_name='Теория'),
        ),
    ]
