# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-08 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0012_videorazboroge_treoryknowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsoge',
            name='code_executor',
        ),
    ]
