# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-08 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0013_remove_questionsoge_code_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsoge',
            name='code_executor',
            field=models.TextField(blank=True, null=True, verbose_name='Испольнитель'),
        ),
    ]
