# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-08 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0014_questionsoge_code_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsoge',
            name='code_executor',
        ),
    ]
