# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-13 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0015_remove_questionsoge_code_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbertaskoge',
            name='type_of_answer',
            field=models.CharField(choices=[('Radio', 'RadioButton'), ('Input', 'Input'), ('NoInp', 'NoInput')], default='Input', max_length=5),
        ),
    ]
