# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-13 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0016_auto_20181014_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsoge',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
