# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-21 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oge', '0017_questionsoge_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='oge.CommentOge')),
                ('task_ege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oge.QuestionsOge', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
