# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0018_commentoge'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsoge',
            name='failed',
            field=models.IntegerField(default=0, verbose_name='Неверные попытки'),
        ),
        migrations.AddField(
            model_name='questionsoge',
            name='passed',
            field=models.IntegerField(default=0, verbose_name='Правильные попытки'),
        ),
    ]
