# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-04 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oge', '0019_auto_20190721_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentoge',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='commentoge',
            name='task_ege',
        ),
        migrations.RemoveField(
            model_name='commentoge',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentOge',
        ),
    ]
