# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-14 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('done_ege_tasks', models.ManyToManyField(blank=True, related_name='ege_done', to='ege.QuestionsEGE', verbose_name='ЕГЭ сделанные')),
                ('done_oge_tasks', models.ManyToManyField(blank=True, related_name='oge_done', to='oge.QuestionsOge', verbose_name='ОГЭ сделанные')),
                ('fail_ege_tasks', models.ManyToManyField(blank=True, related_name='ege_fail', to='ege.QuestionsEGE', verbose_name='ЕГЭ провалено')),
                ('fail_oge_tasks', models.ManyToManyField(blank=True, related_name='oge_fail', to='oge.QuestionsOge', verbose_name='ОГЭ провалено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
