# Generated by Django 5.2 on 2026-04-13 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание курса')),
                ('seo_keywords', models.TextField(blank=True, max_length=160, verbose_name='Keywords')),
                ('stepik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stepik')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Название модуля')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание модуля')),
                ('stepik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stepik')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.learningcourse', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['course', 'sort_order', 'title'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('article', models.TextField(blank=True, null=True, verbose_name='Текст урока')),
                ('youtube_id', models.CharField(blank=True, max_length=75, null=True, verbose_name='YouTube ID')),
                ('rutube_id', models.CharField(blank=True, max_length=75, null=True, verbose_name='Rutube ID')),
                ('stepik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stepik')),
                ('seo_keywords', models.TextField(blank=True, max_length=160, verbose_name='Keywords')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.learningmodule', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['module', 'sort_order', 'title'],
                'unique_together': {('module', 'slug')},
            },
        ),
    ]
