# Generated by Django 5.2 on 2026-04-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20260414_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmodule',
            options={'ordering': ['sort_order', 'course', 'title'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['sort_order', 'module', 'title'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
