# Generated by Django 5.2 on 2026-04-15 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_learningmodule_options_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcourse',
            name='previous_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.learningcourse'),
        ),
    ]
